apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/component: job
    app.kubernetes.io/name: lms-job-20240318060023
  name: lms-job-20240318060023
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
      - args:
        - sh
        - -e
        - -c
        - '# MFE-specific tasks


          (./manage.py lms waffle_flag --list | grep account.redirect_to_microfrontend)
          || ./manage.py lms waffle_flag --create --everyone account.redirect_to_microfrontend

          ./manage.py lms populate_retirement_states




          (./manage.py lms waffle_flag --list | grep learner_profile.redirect_to_microfrontend)
          || ./manage.py lms waffle_flag --create --everyone learner_profile.redirect_to_microfrontend

          site-configuration set --domain=local.edly.io ENABLE_PROFILE_MICROFRONTEND
          true

          site-configuration set --domain=local.edly.io:8000 ENABLE_PROFILE_MICROFRONTEND
          true




          (./manage.py lms waffle_flag --list | grep learner_home_mfe.enabled) ||
          ./manage.py lms waffle_flag learner_home_mfe.enabled --create --everyone




          (./manage.py lms waffle_flag --list | grep course_home.course_home_mfe_progress_tab)
          || ./manage.py lms waffle_flag --create --everyone course_home.course_home_mfe_progress_tab




          (./manage.py lms waffle_flag --list | grep discussions.pages_and_resources_mfe)
          || ./manage.py lms waffle_flag --create --everyone discussions.pages_and_resources_mfe

          (./manage.py lms waffle_flag --list | grep new_core_editors.use_new_text_editor)
          || ./manage.py lms waffle_flag --create --deactivate new_core_editors.use_new_text_editor

          (./manage.py lms waffle_flag --list | grep new_core_editors.use_new_video_editor)
          || ./manage.py lms waffle_flag --create --deactivate new_core_editors.use_new_video_editor

          (./manage.py lms waffle_flag --list | grep new_core_editors.use_new_problem_editor)
          || ./manage.py lms waffle_flag --create --deactivate new_core_editors.use_new_problem_editor




          (./manage.py lms waffle_flag --list | grep discussions.enable_discussions_mfe
          ) || ./manage.py lms waffle_flag --create --everyone discussions.enable_discussions_mfe

          (./manage.py lms waffle_flag --list | grep discussions.enable_learners_tab_in_discussions_mfe
          ) || ./manage.py lms waffle_flag --create --everyone discussions.enable_learners_tab_in_discussions_mfe

          (./manage.py lms waffle_flag --list | grep discussions.enable_moderation_reason_codes
          ) || ./manage.py lms waffle_flag --create --everyone discussions.enable_moderation_reason_codes

          (./manage.py lms waffle_flag --list | grep discussions.enable_reported_content_email_notifications
          ) || ./manage.py lms waffle_flag --create --everyone discussions.enable_reported_content_email_notifications

          (./manage.py lms waffle_flag --list | grep discussions.enable_learners_stats
          ) || ./manage.py lms waffle_flag --create --everyone discussions.enable_learners_stats

          (./manage.py lms waffle_flag --list | grep discussions.enable_new_structure_discussions
          ) || ./manage.py lms waffle_flag --create --everyone discussions.enable_new_structure_discussions




          (./manage.py lms waffle_flag --list | grep openresponseassessment.enhanced_staff_grader)
          || ./manage.py lms waffle_flag --create --everyone openresponseassessment.enhanced_staff_grader'
        env:
        - name: SERVICE_VARIANT
          value: lms
        - name: DJANGO_SETTINGS_MODULE
          value: lms.envs.tutor.production
        image: docker.io/overhangio/openedx:17.0.2
        name: lms
        volumeMounts:
        - mountPath: /openedx/edx-platform/lms/envs/tutor/
          name: settings-lms
        - mountPath: /openedx/edx-platform/cms/envs/tutor/
          name: settings-cms
        - mountPath: /openedx/config
          name: config
      restartPolicy: Never
      volumes:
      - configMap:
          name: openedx-settings-lms
        name: settings-lms
      - configMap:
          name: openedx-settings-cms
        name: settings-cms
      - configMap:
          name: openedx-config
        name: config
  ttlSecondsAfterFinished: 3600
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/component: job
  name: cms-job
spec:
  template:
    spec:
      containers:
      - env:
        - name: SERVICE_VARIANT
          value: cms
        - name: DJANGO_SETTINGS_MODULE
          value: cms.envs.tutor.production
        image: docker.io/overhangio/openedx:17.0.2
        name: cms
        volumeMounts:
        - mountPath: /openedx/edx-platform/lms/envs/tutor/
          name: settings-lms
        - mountPath: /openedx/edx-platform/cms/envs/tutor/
          name: settings-cms
        - mountPath: /openedx/config
          name: config
      restartPolicy: Never
      volumes:
      - configMap:
          name: openedx-settings-lms
        name: settings-lms
      - configMap:
          name: openedx-settings-cms
        name: settings-cms
      - configMap:
          name: openedx-config
        name: config
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/component: job
  name: mysql-job
spec:
  template:
    spec:
      containers:
      - image: docker.io/mysql:8.1.0
        name: mysql
      restartPolicy: Never
