CMS_HOST: studio.local.edly.io
CMS_OAUTH2_SECRET: pF8YwB1oQMTfgaveROIaViG9
CONTACT_EMAIL: contact@local.edly.io
ENABLE_HTTPS: false
ID: leYXJlAy4YWzwivHgRxMee2t
JWT_RSA_PRIVATE_KEY: '-----BEGIN RSA PRIVATE KEY-----

  MIIEowIBAAKCAQEAnYbWFAhEHYJpL0wMgbij84hZfBHkbqiwhzWnXLCCa0+BTKbq

  2idS8LGYGX0c9HQh4NuiO4F9FBrHOS9G+NAhq+5nt0LXmKNL2qVqpz3goV5zfRTs

  8QFb7aTRjaA9hEHDegzQrwOXlU+j1Gr9Z/Q6hsR+MzyMf/HdH+ncwb9PQeMTXRPB

  /4meLemKZSPOaF7oi1iumgwcPIPTvF8pjoiChaFXeS0dXluhUi9kqeH6uO1C0b9M

  QLn656vB2Rh/UFSEOC63c/JlR5pCSm7mJF/FknnEgAybXBgoALUvJN9XM9+zHS8X

  73ji/gxMVMtsmhoRtrkNA7QBdPUcOUnXTboLCQIDAQABAoIBAAc8CePp90WLAjf/

  sZ6u3f9mwS6qBwgwAMoiOYP6aprxZU+hu4J2W4rzVQ1tSgxOCGpHxqfIoXfFZ7s6

  w8h/N99Ut82vqQV5ERhDEDwLDaB2R9k0QfzVjPpuid3hFezXilngxyAVNaZ6qFxZ

  POHD0oDy+urGeptmU7tN+xX+Km6CTptAV0f6kzzbAppkfglUxTGL3PdnAkIWaGjL

  T1D48FFAv09XHYFRXsCfoGuiiJrZEwkPpAdJ+1iWKlOChRFiU8TipjlWC9wVrpZ5

  XC8l4JQAJ9ttqwe+QJMnWurB63O4qiDdv6KiTUiDF/0Zh1KSkmKqwJlfA9t5I2nl

  ckrV2SkCgYEAvG9V03rCRN+DlCoVXykbfc/huh82QChXTOrR4R+Y8ZmRFOgFPDNe

  V9eqZuoaJlJaSIM+PUYqO+rC6NaPC74xlur1+Q7AW+TM7oWzZP/moAOG1lRtM6/I

  s/s4+8hJ7P+D6F9IFOcUDkIju3CU4LGJPv2c6xZMBG2zBYT1C1MF/SUCgYEA1gJm

  hW9Xz0wGJsM4eMKIeqcwQmjkF7jh0ha9QiwIa375vltAcfNcM7Dk0Mos4ef0h/QX

  IS+4P7ZQNecl9ZlcXkdNmeTaf7bKNUNecPs+sexGw4ImO+8q5S4pTxgSab0orDuj

  PMfXwsoGGBG3PZtuI32LutSsiX82urcJWf8V+xUCgYBB8lT/Jj9HC1JpUDEalLBi

  X5aIJNQ/r96dtLCvMPe91hjIUEtEvlWOOJQSYGu2bavbJNNrblrpjUeZZT26xl1k

  i+Z5u4fmoTR3ZaNa/ZQg/Br8d5+gLyz2kD1pILd+kg4ADRiU+Co0s0D+IHB6EqgN

  u4RnYe5Ivnugut9njy7RYQKBgQCiWKfVSaXfR9jSxv2r/kbyZKojdtaxeDs22LEx

  5Z1tjqF+WlMFHowvWl36VaS+quvBxtVVA5JOIsuuWG9fZLvBeW3Q9N8cS1oSFc0r

  AC2LY6Y64hyHEuQDf4UuzyAIvsp//a3TifaPehotYCMVxTdEDRVW4ccRd0PZWMjr

  UKsoEQKBgGbqkWieYCGXWFZJ3fdnU15h4RVYgpSLHQE35rI7LXrSoX9NW5da6ESW

  A/zZVzyzVYZgb+vZE2XkHFsBTfS4h+2LVe7bzk/StxJMnz5SNCz3Jaenwm8RcpRn

  L9AYjj7lVSM1MPAukdTsVJZQQKlGKUZT7zIk9ThwjglDE0n/Xuc2

  -----END RSA PRIVATE KEY-----'
LANGUAGE_CODE: en
LMS_HOST: local.edly.io
MYSQL_ROOT_PASSWORD: ADrTor3l
OPENEDX_MYSQL_PASSWORD: shI43Kgf
OPENEDX_SECRET_KEY: 6iO0CNP9pSmfsfiVEJnBJzOg
PLATFORM_NAME: My Open edX
PLUGINS:
- mfe
- indigo
PLUGIN_INDEXES:
- https://overhang.io/tutor/main
